
###
POST http://localhost:5000/v1/venues/order
Content-Type: application/json

{
  "venueId": "clsdc47cc0002gx3lsjx112r1",
  "billId": 2,
  "orden": "2",
  "mesa": "100",
  "total": "130",
  "status": "0"
}


###
POST http://localhost:5000/v1/venues/comanda
Content-Type: application/json

{
  "venueId": "clsdc47cc0002gx3lsjx112r1",
  "billId": 2,
  "key": "435979",
  "nombre": "., Burrito",
  "orden": "2",
  "cantidad": 1,
  "precio": 77
}

###
# gets new token
POST http://localhost:5000/token
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9zZSIsImlhdCI6MTcwNDkzNjc3Nn0._sUlq1lNaRTuv0GqBQL83G2Z5_FI5Uj4_-cLKf97Lk8"
}

###

DELETE http://localhost:5000/logout
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9zZSIsImlhdCI6MTcwNDkzNjE4MX0.6AADPqEG1G1SYF1HS9MjMk7RLo8hMtvEPbs4e4nfCCc"
}


# returns a token and refresh token
POST http://localhost:5000/login 
Content-Type: application/json

{
"username": "Jose",
"password": "Jose"

}


###

GET http://localhost:5000/venues/1/tables/2?todo=yes
Content-Type: application/json

###

POST http://localhost:5000/bills 
Content-Type: application/json

{"tableNumber": "2"}